'use client';
import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {BookOpen,Plus,Download,Clock,CheckCircle2,Target,RotateCcw,Pencil,Trash2} from 'lucide-react';
import {reviewEvidence} from '@/lib/review';
type Row=Record<string,any>;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function Choice({value,onChange,options}:any){return <Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l]:string[])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
export default function Home(){const [data,setData]=useState<Row>({plans:[],tasks:[],runs:[],revisions:[],reviews:[],completions:[]}),[plan,setPlan]=useState('plan-career'),[tab,setTab]=useState('tasks'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('due'),[from,setFrom]=useState('2026-10-09'),[to,setTo]=useState('2026-12-31'),[metric,setMetric]=useState('all'),[modal,setModal]=useState(''),[form,setForm]=useState<Row>({}),[del,setDel]=useState(''),[delKind,setDelKind]=useState('delete');
async function load(){try{const r=await fetch('/api/data',{cache:'no-store'});const d:Row=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('');}catch(e){setError(String((e as Error).message));}finally{setLoading(false);}}
useEffect(()=>{load();const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();ctx.registerTool({name:'read_diary',description:'현재 서버에 저장된 계획과 할 일, 실행 기록을 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(Object.keys(input).length)throw Error('입력은 빈 객체여야 합니다.');const r=await fetch('/api/data');if(!r.ok)throw Error('조회 실패');return r.json();}},{signal:lifecycle.signal});return()=>lifecycle.abort();},[]);
async function act(action:string,value?:any,id?:string){if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,value,id})});const d:Row=await r.json();if(!r.ok)throw Error(d.error);await load();setModal('');setMessage('서버에 저장했어요.');setTimeout(()=>setMessage(''),3500);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
const p=data.plans.find((x:Row)=>x.id===plan);const tasks=data.tasks.filter((x:Row)=>x.plan_id===plan&&!x.deleted);const runs=data.runs;const summary=reviewEvidence(data.tasks,runs,plan,from,to,today());const scoped=summary.target;const rr=summary.records;const matches=(t:Row,m:string)=>m==='all'||(m==='done'&&t.status==='done')||(m==='late'&&t.status!=='done'&&t.due<today())||(m==='blocked'&&runs.some((r:Row)=>r.task_id===t.id&&r.reason.trim()));
const counts=[['all','할 일',scoped.length],['done','완료',scoped.filter((t:Row)=>matches(t,'done')).length],['late','지연',scoped.filter((t:Row)=>matches(t,'late')).length],['blocked','막힘',scoped.filter((t:Row)=>matches(t,'blocked')).length]];
const est=summary.estimate,actual=summary.actual;
const visible=tasks.filter((t:Row)=>(t.title+' '+t.tags).toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='active'&&t.status!=='done'||matches(t,filter))).sort((a:Row,b:Row)=>sort==='priority'?(['높음','보통','낮음'].indexOf(a.priority)-['높음','보통','낮음'].indexOf(b.priority)||a.id.localeCompare(b.id)):sort==='estimate'?(a.estimate-b.estimate||a.id.localeCompare(b.id)):(a.due.localeCompare(b.due)||a.id.localeCompare(b.id)));
const localTime=(s:string)=>new Date(new Date(s).getTime()+9*60*60*1000).toISOString().slice(0,16);
const openTask=(t?:Row)=>{setForm(t?{...t}:{plan_id:plan,title:'',due:p?.end||today(),priority:'보통',tags:'',estimate:0});setModal('task');};
const openPlan=(old?:Row)=>{setForm(old?{...old}:{title:'',start:today(),end:'2026-12-31',priority:'보통',criterion:'',estimate:0,improvement:''});setModal('plan');};
const field=(key:string,label:string,type='text')=>{
 if(type==='datetime-local'){
  const value=form[key]||'';const date=value.slice(0,10),hour=value.slice(11,13)||'00',minute=value.slice(14,16)||'00';
  const update=(d:string,h:string,m:string)=>setForm({...form,[key]:d?d+'T'+h+':'+m:''});
  return <fieldset className="timefield" key={key}><legend>{label} · 24시간제</legend><div><input aria-label={label+' 날짜'} required type="date" value={date} onChange={e=>update(e.target.value,hour,minute)}/><Choice value={hour} onChange={(h:string)=>update(date,h,minute)} options={Array.from({length:24},(_,i)=>[String(i).padStart(2,'0'),String(i).padStart(2,'0')+'시'])}/><Choice value={minute} onChange={(m:string)=>update(date,hour,m)} options={Array.from({length:60},(_,i)=>[String(i).padStart(2,'0'),String(i).padStart(2,'0')+'분'])}/></div><small>낮 12시 = 12시 / 밤 12시(자정) = 00시</small></fieldset>;
 }
 return <label key={key}>{label}{key==='note'&&<small>공부한 주제나 작업 내용을 적어 주세요. 필수 항목이에요.</small>}<input required={key!=='reason'&&key!=='tags'&&(key!=='improvement'||modal==='review')} type={type} min={type==='number'?0:undefined} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
};
return <main><header><div className="brand"><span className="mark"><BookOpen size={24}/></span><div><strong>플랜두씨</strong><small>나의 계획과 실제를 잇는 다이어리</small></div></div><button className="secondary" onClick={()=>{const blob=new Blob([JSON.stringify({...data,exported_at:new Date().toISOString(),timezone:'Asia/Seoul',unit:'minutes'},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='pds-diary.json';a.click();URL.revokeObjectURL(url);}}><Download size={17}/>전체 내보내기</button></header>
<div className="notice">지금은 로그인이 없어 링크를 아는 사람은 누구나 볼 수 있습니다. 남이 봐도 괜찮은 내용만 넣으세요</div>
{error&&<div role="alert" className="error">{error} <button onClick={load}>다시 불러오기</button></div>}{message&&<div role="status" className="saved">{message}</div>}
<section className="planhead"><div><span className="eyebrow">PLAN / 01</span><h1>{p?.title||'계획을 불러오는 중'}</h1><p>{p?.start} — {p?.end} <span className="badge">{p?.priority}</span></p></div><div className="actions"><button className="secondary" onClick={()=>openPlan(p)}><Pencil size={16}/>계획 수정</button><button onClick={()=>openPlan()}><Plus size={16}/>새 계획</button></div></section>
<div className="planselect"><Choice value={plan} onChange={setPlan} options={data.plans.map((p:Row)=>[p.id,p.title])}/><span>성공 기준: {p?.criterion}</span></div>
{p?.improvement&&<div className="carry">지난 돌아보기에서 가져온 한 줄: {p.improvement}</div>}
<Tabs value={tab} onValueChange={setTab}><TabsList className="nav"><TabsTrigger value="tasks">Plan · 할 일</TabsTrigger><TabsTrigger value="runs">Do · 실행 기록</TabsTrigger><TabsTrigger value="review">See · 돌아보기</TabsTrigger><TabsTrigger value="history">계획 이력</TabsTrigger></TabsList>
<TabsContent value="tasks"><section className="sectionhead"><div><h2>계획을 행동으로</h2><p>예상 시간은 할 일 1건의 기준이에요. 0분인 항목은 직접 정해 주세요.</p></div><button onClick={()=>openTask()}><Plus size={17}/>할 일 추가</button></section><div className="toolbar"><input aria-label="할 일 검색" placeholder="할 일이나 태그 검색" value={query} onChange={e=>setQuery(e.target.value)}/><Choice value={filter} onChange={setFilter} options={ [['all','전체 상태'],['active','진행 중'],['done','완료'],['late','지연'],['blocked','막힘']]}/><Choice value={sort} onChange={setSort} options={ [['due','마감일 빠른 순'],['priority','우선순위 높은 순'],['estimate','예상 시간 적은 순']]}/></div><p className="meta">같은 값은 ID 오름차순으로 정렬 · {visible.length}개</p><div className="tasklist">{visible.map((t:Row)=><article className="task" key={t.id}><button className={'check '+(t.status==='done'?'checked':'')} aria-label={t.status==='done'?'완료 되돌리기':'완료하기'} disabled={busy} onClick={()=>act(t.status==='done'?'reopen':'complete',undefined,t.id)}>{t.status==='done'&&<CheckCircle2 size={22}/>}</button><div className="taskbody"><h3 className={t.status==='done'?'done':''}>{t.title}</h3><p><span className="badge">{t.priority}</span> {t.due} <span>· 예상 {t.estimate}분</span> <span>· 실제 {runs.filter((r:Row)=>r.task_id===t.id).reduce((a:number,r:Row)=>a+r.minutes,0)}분</span></p><div className="tags">{t.tags.split(',').filter(Boolean).map((s:string)=><span key={s}>{s}</span>)}</div><small>ID: {t.id}</small></div><div className="taskactions"><button className="secondary" onClick={()=>{setForm({task_id:t.id,start:'',end:'',reason:'',note:'',request_key:crypto.randomUUID()});setModal('run');}}><Clock size={16}/>기록</button><button className="icon" aria-label="수정" onClick={()=>openTask(t)}><Pencil size={17}/></button><button className="icon" aria-label="삭제" onClick={()=>{setDelKind('delete');setDel(t.id)}}><Trash2 size={17}/></button></div></article>)}</div>{!visible.length&&<div className="empty">{loading?'자료를 불러오는 중이에요.':'조건에 맞는 할 일이 없어요.'}</div>}</TabsContent>
<TabsContent value="runs"><section className="sectionhead"><div><h2>실제로 한 일을 남겨요</h2><p>실행 기록은 계획을 바꾸지 않아요. 시각은 서울 시간으로 입력합니다. 계획 기간이 아니라 한 번의 실제 작업 시간을 적어요.</p></div></section>{runs.filter((r:Row)=>tasks.some((t:Row)=>t.id===r.task_id)).map((r:Row)=><article className="record" key={r.id}><h3>{tasks.find((t:Row)=>t.id===r.task_id)?.title}<span className="badge">{r.minutes}분</span></h3><p>{new Date(r.start).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} ~ {new Date(r.end).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p><p>{r.note||'학습 내용 미기입'}</p><p className="reason">막힌 이유: {r.reason||'없음'}</p><small>할 일 ID: {r.task_id} · 기록 ID: {r.id}</small>{(r.minutes>1440||new Date(r.end)>new Date())&&<p className="error">작업 시간 대신 계획 기간이 들어간 것 같아요. 실제 시각으로 수정해 주세요.</p>}<div className="actions"><button className="secondary" onClick={()=>{setForm({...r,start:localTime(r.start),end:localTime(r.end)});setModal('run')}}><Pencil size={16}/>기록 수정</button><button className="secondary" onClick={()=>{setDelKind('delete-run');setDel(r.id)}}><Trash2 size={16}/>기록 삭제</button></div></article>)}{!runs.some((r:Row)=>tasks.some((t:Row)=>t.id===r.task_id))&&<div className="empty"><Clock/><h3>첫 실행 기록을 기다리고 있어요</h3><p>할 일 옆 ‘기록’을 눌러 실제로 공부한 내용을 입력하세요.<br/>제출에는 실제 기록 3건 이상이 필요해요.</p></div>}</TabsContent>
<TabsContent value="review"><section className="sectionhead"><div><h2>계획과 실제 사이</h2><p>선택한 계획에서 마감일이 아래 기간에 포함된 할 일을 집계합니다.</p></div></section><div className="period"><label>시작<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>끝<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><span>지연 판단: 서울 기준 {today()}</span></div><div className="metrics">{counts.map(([m,l,n])=><button className={'metric '+(metric===m?'selected':'')} key={m} onClick={()=>setMetric(String(m))}><span>{l}</span><strong>{n}</strong><small>근거 할 일 보기</small></button>)}</div><div className="times">{[['예상 시간',est],['실제 시간',actual],['차이 · 실제 − 예상',actual-est]].map(([l,n])=><button key={l} onClick={()=>setMetric(l==='예상 시간'?'all':'time')}><span>{l}</span><strong>{n}<small>분</small></strong></button>)}</div><div className="evidence"><h3>숫자의 근거</h3>{metric==='time'?rr.map((r:Row)=><p key={r.id}>{tasks.find((t:Row)=>t.id===r.task_id)?.title} · {r.minutes}분 · {new Date(r.start).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})} · {r.note} <small>{r.id}</small></p>):scoped.filter((t:Row)=>matches(t,metric)).map((t:Row)=><p key={t.id}>{t.title} · {t.status==='done'?'완료':'진행 중'} · 예상 {t.estimate}분 · {t.due}<small>{t.id}</small>{metric==='blocked'&&runs.filter((r:Row)=>r.task_id===t.id&&r.reason.trim()).map((r:Row)=><span key={r.id}>막힌 이유: {r.reason}</span>)}</p>)}{(metric==='time'?rr:scoped.filter((t:Row)=>matches(t,metric))).length===0&&<p>해당 기록이 없어요. 합계는 0입니다.</p>}</div><div className="next"><Target/><div><h3>다음 계획에 가져갈 한 가지</h3><p>예상보다 오래 걸린 이유를 보고, 다음에 바꿀 행동을 한 줄로 적어요.</p></div><button onClick={()=>{setForm({plan_id:plan,start:from,end:to,improvement:'',title:'다음 취업 준비 계획',next_start:to,next_end:to});setModal('review');}}>다음 계획 만들기</button></div>{data.reviews.filter((r:Row)=>r.plan_id===plan).map((r:Row)=><article className="record" key={r.id}><p>{r.improvement}</p><button className="secondary" onClick={()=>{setPlan(r.next_plan_id);setTab('tasks');}}>연결된 다음 계획 열기</button></article>)}</TabsContent>
<TabsContent value="history"><section className="sectionhead"><div><h2>처음의 계획도 남아 있어요</h2><p>수정할 때마다 바꾸기 전 계획을 따로 저장합니다. 현재 예상 시간: {p?.estimate}분</p></div></section>{data.revisions.filter((r:Row)=>r.plan_id===plan).map((r:Row)=>{const v=JSON.parse(r.snapshot);return <article className="record" key={r.id}><small>{new Date(r.at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} 수정 전</small><h3>{v.title}</h3><p>{v.start} ~ {v.end} · {v.priority} · 예상 {v.estimate}분</p><p>{v.criterion}</p><p>{v.improvement}</p><small>계획 ID: {r.plan_id}</small></article>})}{!data.revisions.some((r:Row)=>r.plan_id===plan)&&<div className="empty">아직 수정 이력이 없어요. ‘계획 수정’ 후 이전 내용이 여기에 남아요.</div>}</TabsContent></Tabs>
<footer>Plan · Do · See <span>시간 단위: 분 / 표시 시간대: Asia/Seoul / 서버 DB 저장</span></footer>
<Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal('')}}><DialogContent className="formdialog"><DialogHeader><DialogTitle>{ {task:'할 일',plan:'계획',run:'실행 기록',review:'다음 계획으로'}[modal]}</DialogTitle></DialogHeader><form onSubmit={e=>{e.preventDefault();let v={...form};if(modal==='run'){v.start=form.start+'+09:00';v.end=form.end+'+09:00';}act(modal,v);}}>{modal==='task'&&<>{field('title','할 일')}{field('due','마감일','date')}<label>우선순위<Choice value={form.priority} onChange={(v:string)=>setForm({...form,priority:v})} options={ [['높음','높음'],['보통','보통'],['낮음','낮음']]}/></label>{field('tags','태그 · 쉼표로 구분')}{field('estimate','예상 시간 · 분','number')}</>}{modal==='plan'&&<>{field('title','계획 제목')}{field('start','시작일','date')}{field('end','종료일','date')}<label>우선순위<Choice value={form.priority} onChange={(v:string)=>setForm({...form,priority:v})} options={ [['높음','높음'],['보통','보통'],['낮음','낮음']]}/></label>{field('criterion','성공 기준')}{field('estimate','계획 예상 시간 · 분','number')}{field('improvement','지난 계획의 개선점')}</>}{modal==='run'&&<><p>{tasks.find((t:Row)=>t.id===form.task_id)?.title}</p>{field('start','시작 시각 · 서울','datetime-local')}{field('end','끝난 시각 · 서울','datetime-local')}{field('note','실제로 한 내용')}{field('reason','막힌 이유 · 없으면 비워 두세요')}<p className="notice">예: 실제로 밤 9시~10시 공부했다면 같은 날짜의 21:00~22:00을 입력해요. 미래 시각과 24시간을 넘는 기록은 저장하지 않아요.</p><p className="meta">{form.start&&form.end&&Number.isFinite(Date.parse(form.start))&&Number.isFinite(Date.parse(form.end))?'이번 기록: '+Math.round((Date.parse(form.end)-Date.parse(form.start))/60000)+'분 · ':''}실제 시간은 시작·끝 시각에서 분으로 계산해요. 완료 상태는 할 일의 체크 버튼으로 바꿔요.</p></>}{modal==='review'&&<>{field('improvement','다음에 바꿀 행동 한 줄')}{field('title','다음 계획 제목')}{field('next_start','다음 시작일','date')}{field('next_end','다음 종료일','date')}</>}{error&&<p role="alert" className="error">{error}</p>}<button type="submit" disabled={busy}>{busy?'저장 중…':'서버에 저장'}</button></form></DialogContent></Dialog>
<AlertDialog open={!!del} onOpenChange={v=>{if(!v)setDel('')}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{delKind==='delete-run'?'이 실행 기록을 삭제할까요?':'이 할 일을 삭제할까요?'}</AlertDialogTitle></AlertDialogHeader><p>{delKind==='delete-run'?'이 기록과 소요 시간이 삭제돼요. 할 일의 완료 상태는 유지됩니다.':'목록과 집계에서 제외해요. 전체 내보내기에는 보관됩니다.'}</p><AlertDialogFooter><AlertDialogCancel>취소</AlertDialogCancel><AlertDialogAction onClick={()=>{act(delKind,undefined,del);setDel('');}}>삭제</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
</main>}
